'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import styles from './Search.module.css';
type User={id:string;username:string;displayName:string|null;avatarUrl:string|null;followers:number;isFollowing:boolean;isSelf:boolean};
export default function SearchPage(){const[q,setQ]=useState(''),[users,setUsers]=useState<User[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState<string|null>(null);
useEffect(()=>{const t=setTimeout(async()=>{const value=q.trim();if(!value){setUsers([]);setLoading(false);setError('');return}setLoading(true);setError('');try{const r=await fetch(`/api/users/search?q=${encodeURIComponent(value.replace(/^@/,''))}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Search failed');setUsers(d.users??[])}catch(e){setError(e instanceof Error?e.message:'Ошибка поиска');setUsers([])}finally{setLoading(false)}},250);return()=>clearTimeout(t)},[q]);
async function toggleFollow(u:User){setBusy(u.id);setError('');try{const r=await fetch(`/api/users/${encodeURIComponent(u.username)}/follow`,{method:'POST'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Не удалось изменить подписку');setUsers(list=>list.map(x=>x.id===u.id?{...x,isFollowing:d.following,followers:d.count}:x))}catch(e){setError(e instanceof Error?e.message:'Не удалось изменить подписку')}finally{setBusy(null)}}
return <main className="shell"><aside className="sidebar"><div className="brand">NEXA<span>.</span></div><nav><Link href="/">Home</Link><Link className="active" href="/search">Search</Link><Link href="/messages">Messages</Link><Link href="/notifications">Notifications</Link><Link href="/profile">Profile</Link></nav></aside><section className="feed"><header className="topbar"><div><p className="eyebrow">DISCOVER</p><h1>Поиск</h1></div></header><div className={styles.searchBox}><span>⌕</span><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Имя или @username" aria-label="Поиск пользователей"/></div>{loading&&<p className="search-state">Ищем…</p>}{error&&<p className="error">{error}</p>}{!loading&&q.trim()&&users.length===0&&!error&&<p className="search-state">Пользователи не найдены.</p>}<section>{users.map(u=><div className={styles.result} key={u.id}><Link className={styles.resultLink} href={`/users/${encodeURIComponent(u.username)}`}><div className="mini-avatar gradient">{u.avatarUrl?<img src={u.avatarUrl} alt=""/>:(u.displayName||u.username)[0]?.toUpperCase()}</div><div className={styles.resultInfo}><strong>{u.displayName||u.username}</strong><span>@{u.username} · {u.followers} подписчиков</span></div></Link>{!u.isSelf&&<button className={`${styles.follow} ${u.isFollowing?styles.following:''}`} disabled={busy===u.id} onClick={()=>toggleFollow(u)}>{busy===u.id?'…':u.isFollowing?'Вы подписаны':'Подписаться'}</button>}<span className={styles.arrow}>→</span></div>)}</section></section></main>}
