services:
  - type: web
    name: nexa
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AUTH_SECRET
        sync: false
