'use client';
import Link from 'next/link'; import {useEffect,useState} from 'react'; import {useParams} from 'next/navigation';
type Post={id:string;content:string;created_at:string;username:string;like_count:number;comment_count:number;liked:boolean};
type Profile={id:string;username:string;displayName:string|null;bio:string|null;avatarUrl:string|null;createdAt:string};
export default function PublicProfile(){const params=useParams<{username:string}>(),username=Array.isArray(params.username)?params.username[0]:params.username;const[profile,setProfile]=useState<Profile|null>(null),[posts,setPosts]=useState<Post[]>([]),[followers,setFollowers]=useState(0),[following,setFollowing]=useState(0),[isFollowing,setIsFollowing]=useState(false),[isSelf,setIsSelf]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{const r=await fetch(`/api/users/${encodeURIComponent(username)}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Пользователь не найден');setProfile(d.user);setPosts(d.posts||[]);setFollowers(d.followers||0);setFollowing(d.following||0);setIsFollowing(!!d.isFollowing);setIsSelf(!!d.isSelf)};
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[username]);
 const follow=async()=>{if(!profile)return;const r=await fetch(`/api/users/${profile.id}/follow`,{method:'POST'}),d=await r.json();if(!r.ok){setError(d.error||'Не удалось изменить подписку');return}setIsFollowing(d.following);setFollowers(d.count)};
 if(loading)return <main className="shell"><section className="feed profile-loading"><p>Загрузка профиля…</p></section></main>;
 if(error||!profile)return <main className="shell"><section className="feed profile-loading"><h1>Профиль не найден</h1><p>{error}</p><Link href="/">Вернуться в NEXA</Link></section></main>;
 const name=profile.displayName||profile.username,initial=name[0]?.toUpperCase()||'N';
 return <main className="shell"><aside className="sidebar"><div className="brand">NEXA<span>.</span></div><nav><Link href="/">Home</Link><Link className="active" href={`/users/${profile.username}`}>Profile</Link></nav></aside><section className="feed"><header className="topbar"><div><p className="eyebrow">NEXA USER</p><h1>Профиль</h1></div><Link className="avatar" href="/">N</Link></header><section className="profile-hero"><div className="profile-cover"/><div className="profile-main"><div className="profile-avatar gradient">{profile.avatarUrl?<img src={profile.avatarUrl} alt="Аватар"/>:initial}</div><div className="profile-actions">{isSelf?<Link className="profile-action primary" href="/profile">Редактировать</Link>:<button className="profile-action primary" onClick={follow}>{isFollowing?'Отписаться':'Подписаться'}</button>}</div><h2>{name}</h2><p className="profile-username">@{profile.username}</p>{profile.bio?<p className="profile-bio">{profile.bio}</p>:null}<div className="profile-stats"><span><b>{followers}</b> подписчиков</span><span><b>{following}</b> подписок</span></div></div></section><div className="profile-tabs"><button className="selected">Посты</button><button>Медиа</button><button>Лайки</button></div>{posts.length?posts.map(p=><article className="post" key={p.id}><div className="post-head"><div className="mini-avatar gradient">{initial}</div><div><strong>{name}</strong><span>@{p.username} · {new Date(p.created_at).toLocaleString()}</span></div></div><p className="post-text">{p.content}</p><div className="post-footer"><span>♥ {p.like_count}</span><span>💬 {p.comment_count}</span></div></article>):<section className="profile-empty"><div className="profile-empty-icon">✦</div><h3>Пока нет публикаций</h3><p>Здесь появятся записи пользователя.</p></section>}</section></main>;
}
