'use client';
import Link from 'next/link';
import { Suspense, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import NotificationCenter from '@/components/NotificationCenter';
import styles from './home.module.css';

type User={id:string;username:string;email:string};
type Comment={id:string;content:string;created_at:string;user_id:string;username:string};
type Post={id:string;content:string;created_at:string;user_id:string;username:string;like_count:number;comment_count:number;liked:boolean;media_url?:string|null;media_type?:string|null};
type Story={id:string;user_id:string;username:string;media_url:string;media_type:string;caption:string;created_at:string;expires_at:string;view_count:number};

function HomeContent(){
 const searchParams=useSearchParams(), targetPost=searchParams.get('post');
 const [user,setUser]=useState<User|null>(null),[posts,setPosts]=useState<Post[]>([]),[stories,setStories]=useState<Story[]>([]),[content,setContent]=useState(''),[comments,setComments]=useState<Record<string,Comment[]>>({}),[commentText,setCommentText]=useState<Record<string,string>>({}),[open,setOpen]=useState<Record<string,boolean>>({}),[saved,setSaved]=useState<Record<string,boolean>>({}),[mode,setMode]=useState<'for-you'|'following'>('for-you'),[loading,setLoading]=useState(true),[posting,setPosting]=useState(false),[storyUploading,setStoryUploading]=useState(false),[storyViewer,setStoryViewer]=useState<Story|null>(null),[error,setError]=useState('');
 const load=async(m=mode)=>{try{const r=await fetch(m==='following'?'/api/feed/following':'/api/posts',{cache:'no-store'}),d=await r.json();setPosts(d.posts??[]);if(!r.ok&&m==='following')setError('Подпишись на пользователей, чтобы увидеть их публикации.')}catch{setError('Не удалось загрузить ленту')}};
 const loadStories=async()=>{try{const r=await fetch('/api/stories',{cache:'no-store'});if(r.ok){const d=await r.json();setStories(d.stories??[])}}catch{}};
 useEffect(()=>{Promise.all([fetch('/api/auth/me',{cache:'no-store'}).then(r=>r.json()),fetch('/api/posts',{cache:'no-store'}).then(r=>r.json()),fetch('/api/stories',{cache:'no-store'}).then(r=>r.ok?r.json():{stories:[]})]).then(([m,p,s])=>{setUser(m.user??null);setPosts(p.posts??[]);setStories(s.stories??[])}).catch(()=>setError('Не удалось загрузить ленту')).finally(()=>setLoading(false));try{const x=JSON.parse(localStorage.getItem('nexa_saved_posts')||'[]');setSaved(Object.fromEntries(x.map((id:string)=>[id,true])))}catch{}},[]);
 useEffect(()=>{if(!targetPost||loading)return;const post=posts.find(p=>p.id===targetPost);if(!post)return;setOpen(x=>({...x,[targetPost]:true}));if(!comments[targetPost])fetch(`/api/posts/${targetPost}/comments`,{cache:'no-store'}).then(r=>r.json()).then(d=>setComments(x=>({...x,[targetPost]:d.comments??[]}))).catch(()=>{});requestAnimationFrame(()=>document.getElementById(`post-${targetPost}`)?.scrollIntoView({behavior:'smooth',block:'center'}))},[targetPost,loading,posts]);
 const initial=(user?.username?.[0]??'N').toUpperCase();
 const createPost=async()=>{if(!user)return;setPosting(true);const r=await fetch('/api/posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content})}),d=await r.json();if(!r.ok)setError(d.error||'Ошибка публикации');else{setContent('');await load('for-you')}setPosting(false)};
 const createStory=async(file:File)=>{if(!user)return;setStoryUploading(true);try{if(file.size>50*1024*1024)throw new Error('История не может быть больше 50 МБ');if(!file.type.startsWith('image/')&&!file.type.startsWith('video/'))throw new Error('Для истории выбери фото или видео');const p=await fetch('/api/media/presign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scope:'stories',fileName:file.name,mimeType:file.type,fileSize:file.size})});const pd=await p.json();if(!p.ok)throw new Error(pd.error||'Не удалось подготовить загрузку');const upload=await fetch(pd.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!upload.ok)throw new Error('Не удалось загрузить файл');const r=await fetch('/api/stories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mediaKey:pd.key,mediaType:pd.mediaType,caption:''})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Не удалось создать историю');await loadStories()}catch(e){setError(e instanceof Error?e.message:'Не удалось создать историю')}finally{setStoryUploading(false)}};
 const openStory=async(s:Story)=>{setStoryViewer(s);try{await fetch(`/api/stories/${s.id}/view`,{method:'POST'});setStories(x=>x.map(q=>q.id===s.id?{...q,view_count:q.view_count+1}:q))}catch{}};
 const like=async(p:Post)=>{if(!user)return setError('Войдите, чтобы ставить лайки');const r=await fetch(`/api/posts/${p.id}/like`,{method:'POST'});if(r.ok){const d=await r.json();setPosts(x=>x.map(q=>q.id===p.id?{...q,liked:d.liked,like_count:d.count}:q))}};
 const toggleComments=async(id:string)=>{const n=!open[id];setOpen(x=>({...x,[id]:n}));if(n&&!comments[id]){const r=await fetch(`/api/posts/${id}/comments`),d=await r.json();setComments(x=>({...x,[id]:d.comments??[]}))}};
 const addComment=async(id:string)=>{if(!user)return setError('Войдите, чтобы комментировать');const text=(commentText[id]??'').trim();if(!text)return;const r=await fetch(`/api/posts/${id}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:text})}),d=await r.json();if(!r.ok)return setError(d.error||'Ошибка комментария');setComments(x=>({...x,[id]:[...(x[id]??[]),d.comment]}));setPosts(x=>x.map(p=>p.id===id?{...p,comment_count:p.comment_count+1}:p));setCommentText(x=>({...x,[id]:''}))};
 const share=async(p:Post)=>{const url=`${window.location.origin}/?post=${p.id}`;try{if(navigator.share)await navigator.share({title:`@${p.username} в NEXA`,text:p.content||'Фото в NEXA',url});else await navigator.clipboard.writeText(url)}catch{}};
 const toggleSave=(id:string)=>{const next=!saved[id],nextState={...saved,[id]:next};setSaved(nextState);try{localStorage.setItem('nexa_saved_posts',JSON.stringify(Object.keys(nextState).filter(k=>nextState[k])))}catch{}};
 return <main className={styles.app}><aside className={styles.sidebar}><Link className={styles.logo} href="/">NEXA<span>.</span></Link><nav className={styles.nav}><Link className={styles.active} href="/">⌂<small>Главная</small></Link><Link href="/search">⌕<small>Поиск</small></Link><Link href="/messages">✉<small>Сообщения</small></Link><Link href="/notifications">♡<small>Уведомления</small></Link><Link href={user?'/profile':'/auth/login'}>●<small>Профиль</small></Link><Link href="/friends">♧<small>Друзья</small></Link><Link href="/communities">◈<small>Сообщества</small></Link><Link href="/media">▣<small>Медиа</small></Link><Link href="/bookmarks">★<small>Сохранённое</small></Link><Link href="/settings">⚙<small>Настройки</small></Link></nav>{!loading&&!user&&<Link className={styles.create} href="/auth/register">Создать аккаунт</Link>}</aside>
 <section className={styles.feed}><header className={styles.header}><div><span className={styles.kicker}>NEXA / SOCIAL</span><h1>Главная</h1></div><div className={styles.headerActions}><NotificationCenter/><Link className={styles.avatar} href={user?'/profile':'/auth/login'}>{initial}</Link></div></header>
 <section className={styles.stories} aria-label="Истории"><div className={styles.storiesTop}><div><span className={styles.kicker}>24 ЧАСА</span><h2>Истории</h2></div>{user&&<label className={styles.addStory}>{storyUploading?'Загрузка…':'＋ Добавить'}<input type="file" accept="image/*,video/*" disabled={storyUploading} onChange={e=>{const f=e.target.files?.[0];if(f)createStory(f);e.currentTarget.value=''}}/></label>}</div><div className={styles.storyRail}>{user&&<button className={styles.storyAddCard} type="button" onClick={()=>document.getElementById('story-file')?.click()}><span>{initial}</span><b>Моя история</b><small>Фото или видео</small></button>}{stories.map(s=><button key={s.id} type="button" className={styles.storyCard} onClick={()=>openStory(s)}><img src={s.media_url} alt=""/><span className={styles.storyShade}/><strong>{s.username}</strong><small>{s.view_count} просмотров</small></button>)}</div>{!stories.length&&<p className={styles.storiesEmpty}>Добавь первую историю — она будет видна 24 часа.</p>}<input id="story-file" className={styles.hiddenFile} type="file" accept="image/*,video/*" disabled={storyUploading} onChange={e=>{const f=e.target.files?.[0];if(f)createStory(f);e.currentTarget.value=''}}/></section>
 <div className={styles.tabs}><button className={mode==='for-you'?styles.selected:''} onClick={()=>{setMode('for-you');load('for-you')}}>Для тебя</button><button className={mode==='following'?styles.selected:''} onClick={()=>{setMode('following');load('following')}} disabled={!user}>Подписки</button></div>
 {user?<article className={styles.composer}><div className={styles.avatarSm}>{initial}</div><div className={styles.composeBody}><textarea value={content} onChange={e=>setContent(e.target.value)} maxLength={2000} placeholder="Что нового? Поделись с NEXA…"/><div className={styles.composeBottom}><span>{content.length}/2000</span><button onClick={createPost} disabled={posting||!content.trim()}>{posting?'Публикация…':'Опубликовать'}</button></div></div></article>:<article className={styles.guest}><div><span className={styles.kicker}>WELCOME TO NEXA</span><h2>Твоё пространство. Твои люди.</h2><p>Создай аккаунт, чтобы публиковать, подписываться и общаться.</p></div><Link href="/auth/register">Войти в NEXA →</Link></article>}
 {error&&<div className={styles.error}>{error}<button onClick={()=>setError('')}>×</button></div>}
 {loading&&<div className={styles.loading}><span/><span/><span/></div>}
 {!loading&&posts.length===0&&<article className={styles.empty}><div>✦</div><h3>{mode==='following'?'Лента подписок пока пуста':'Пока нет публикаций'}</h3><p>{mode==='following'?'Подпишись на людей, чтобы собрать свою ленту.':'Стань первым, кто опубликует что-нибудь в NEXA.'}</p></article>}
 {posts.map(p=><article className={styles.post} id={`post-${p.id}`} key={p.id}><div className={styles.postHead}><Link href={`/users/${p.username}`} className={`${styles.postAvatar} ${styles.gradient}`}>{p.username[0]?.toUpperCase()??'N'}</Link><div className={styles.identity}><Link href={`/users/${p.username}`}><strong>{p.username}</strong></Link><span>@{p.username} · {new Date(p.created_at).toLocaleString()}</span></div><button className={styles.more} onClick={()=>share(p)}>↗</button></div>{p.content&&<p className={styles.postText}>{p.content}</p>}{p.media_url&&<img src={p.media_url} alt="Фото публикации" style={{display:'block',width:'100%',maxHeight:620,objectFit:'cover',borderRadius:20,marginTop:12,border:'1px solid rgba(255,255,255,.08)'}}/>}<div className={styles.actions}><button className={p.liked?styles.liked:''} onClick={()=>like(p)}>♥ <span>{p.like_count??0}</span></button><button onClick={()=>toggleComments(p.id)}>◌ <span>{p.comment_count??0}</span></button><button onClick={()=>share(p)}>↗ <span>Поделиться</span></button><button className={saved[p.id]?styles.saved:''} onClick={()=>toggleSave(p.id)}>{saved[p.id]?'★':'☆'} <span>{saved[p.id]?'Сохранено':'Сохранить'}</span></button></div>{open[p.id]&&<div className={styles.comments}>{(comments[p.id]??[]).map(c=><div className={styles.comment} key={c.id}><b>{c.username}</b><span>{c.content}</span></div>)}{user&&<div className={styles.commentForm}><input value={commentText[p.id]??''} onChange={e=>setCommentText(x=>({...x,[p.id]:e.target.value}))} maxLength={1000} placeholder="Напиши комментарий…"/><button onClick={()=>addComment(p.id)}>Отправить</button></div>}</div>}</article>)}
 {storyViewer&&<div className={styles.storyViewer} role="dialog" aria-modal="true" onClick={()=>setStoryViewer(null)}><div className={styles.storyViewerInner} onClick={e=>e.stopPropagation()}><button className={styles.storyClose} onClick={()=>setStoryViewer(null)}>×</button>{storyViewer.media_type==='video'?<video src={storyViewer.media_url} controls autoPlay playsInline/>:<img src={storyViewer.media_url} alt={storyViewer.caption||'История'}/>}<div className={styles.storyViewerMeta}><b>@{storyViewer.username}</b>{storyViewer.caption&&<span>{storyViewer.caption}</span>}<small>{storyViewer.view_count} просмотров</small></div></div></div>}
 </section></main>}
export default function Home(){return <Suspense fallback={<main className="shell"><section className="feed"><p>Загрузка NEXA…</p></section></main>}><HomeContent/></Suspense>}
