'use client';

import styles from './profile.module.css';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { useRouter } from 'next/navigation';

type User = { id:string; username:string; email:string; displayName:string; bio:string; avatarUrl:string|null; createdAt:string };
type Post = { id:number|string; content:string; created_at:string; user_id:string; username?:string; like_count:number; comment_count:number; liked:boolean; media_url?:string|null; media_type?:string|null };
type Comment = { id:string; content:string; created_at:string; user_id:string; username:string };
type Person = { id:string; username:string; displayName:string|null; avatarUrl:string|null };

function compressImage(file:File):Promise<string>{
 return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject();reader.onload=()=>{const image=new Image();image.onerror=()=>reject();image.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const ctx=canvas.getContext('2d');if(!ctx)return reject();ctx.drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.82))};image.src=String(reader.result)};reader.readAsDataURL(file)})
}

export default function ProfilePage(){
 const router=useRouter(),fileInputRef=useRef<HTMLInputElement>(null),photoInputRef=useRef<HTMLInputElement>(null);
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 const [posts,setPosts]=useState<Post[]>([]),[postsLoading,setPostsLoading]=useState(true),[followers,setFollowers]=useState<Person[]>([]),[following,setFollowing]=useState<Person[]>([]);
 const [connections,setConnections]=useState<'followers'|'following'|null>(null),[connectionsLoading,setConnectionsLoading]=useState(false),[tab,setTab]=useState<'posts'|'media'>('posts');
 const [form,setForm]=useState({displayName:'',bio:'',avatarUrl:''});
 const [comments,setComments]=useState<Record<string,Comment[]>>({}),[openComments,setOpenComments]=useState<Record<string,boolean>>({}),[commentText,setCommentText]=useState<Record<string,string>>({});

 async function loadPosts(uid:string){try{const r=await fetch('/api/posts',{cache:'no-store'});const d=await r.json();if(r.ok)setPosts((Array.isArray(d.posts)?d.posts:[]).filter((p:Post)=>String(p.user_id)===String(uid)))}catch{}finally{setPostsLoading(false)}}
 useEffect(()=>{let alive=true;fetch('/api/auth/me',{cache:'no-store'}).then(r=>r.json()).then(async me=>{if(!alive)return;if(!me.user){router.replace('/auth/login');return}setUser(me.user);setForm({displayName:me.user.displayName||me.user.username,bio:me.user.bio||'',avatarUrl:me.user.avatarUrl||''});setLoading(false);loadPosts(me.user.id);
  try{const [fr,fg]=await Promise.all([fetch(`/api/users/${encodeURIComponent(me.user.username)}/connections?type=followers`,{cache:'no-store'}),fetch(`/api/users/${encodeURIComponent(me.user.username)}/connections?type=following`,{cache:'no-store'})]);const [fd,gd]=await Promise.all([fr.json(),fg.json()]);if(alive){if(fr.ok)setFollowers(Array.isArray(fd.users)?fd.users:[]);if(fg.ok)setFollowing(Array.isArray(gd.users)?gd.users:[])}}catch{}
 }).catch(()=>{if(alive){router.replace('/auth/login');setLoading(false);setPostsLoading(false)}});return()=>{alive=false}},[router]);

 useEffect(()=>{if(!connections)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}},[connections]);
 async function refreshConnections(type:'followers'|'following'){if(!user)return;setConnections(type);setConnectionsLoading(true);try{const r=await fetch(`/api/users/${encodeURIComponent(user.username)}/connections?type=${type}`,{cache:'no-store'}),d=await r.json();if(r.ok){const list=Array.isArray(d.users)?d.users:[];if(type==='followers')setFollowers(list);else setFollowing(list)}}finally{setConnectionsLoading(false)}}
 async function chooseAvatar(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!file.type.startsWith('image/')||file.size>10*1024*1024){setError('Выбери изображение до 10 МБ.');return}try{const data=await compressImage(file);if(data.length>290000){setError('Аватар получился слишком большим.');return}setForm(v=>({...v,avatarUrl:data}));setError('')}catch{setError('Не удалось обработать изображение.')}}
 async function save(e:React.FormEvent){e.preventDefault();if(!form.displayName.trim()){setError('Имя не может быть пустым.');return}setSaving(true);setError('');try{const r=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Не удалось сохранить');setUser(d.user);setForm({displayName:d.user.displayName||d.user.username,bio:d.user.bio||'',avatarUrl:d.user.avatarUrl||''});setEditing(false)}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить изменения.')}finally{setSaving(false)}}
 async function uploadPhotos(e:React.ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;setUploading(true);setError('');try{for(const file of files){if(!file.type.startsWith('image/'))continue;if(file.size>20*1024*1024){setError(`Файл ${file.name} слишком большой.`);continue}const data=await compressImage(file);if(data.length>5_800_000){setError(`Фото ${file.name} получилось слишком большим.`);continue}const r=await fetch('/api/posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:'',mediaUrl:data,mediaType:'image'})});const d=await r.json();if(!r.ok)throw new Error(d.error||`Не удалось загрузить ${file.name}`)}await loadPosts(user!.id);setTab('media')}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить фото')}finally{setUploading(false)}}
 async function like(post:Post){const r=await fetch(`/api/posts/${post.id}/like`,{method:'POST'});if(r.ok){const d=await r.json();setPosts(x=>x.map(p=>p.id===post.id?{...p,liked:d.liked,like_count:d.count}:p))}}
 async function toggleComments(post:Post){const next=!openComments[String(post.id)];setOpenComments(x=>({...x,[String(post.id)]:next}));if(next&&!comments[String(post.id)]){const r=await fetch(`/api/posts/${post.id}/comments`,{cache:'no-store'}),d=await r.json();if(r.ok)setComments(x=>({...x,[String(post.id)]:d.comments||[]}))}}
 async function addComment(post:Post){const id=String(post.id),text=(commentText[id]||'').trim();if(!text)return;const r=await fetch(`/api/posts/${post.id}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:text})}),d=await r.json();if(!r.ok){setError(d.error||'Не удалось добавить комментарий');return}setComments(x=>({...x,[id]:[...(x[id]||[]),d.comment]}));setPosts(x=>x.map(p=>p.id===post.id?{...p,comment_count:p.comment_count+1}:p));setCommentText(x=>({...x,[id]:''}))}
 async function share(post:Post){const url=`${window.location.origin}/?post=${post.id}`;try{if(navigator.share)await navigator.share({title:`@${user?.username} в NEXA`,text:post.content||'Фото в NEXA',url});else await navigator.clipboard.writeText(url)}catch{}}
 const initial=(user?.displayName||user?.username||'N')[0]?.toUpperCase()||'N';
 if(loading)return <main className="shell"><section className="feed profile-loading"><p>Загрузка профиля…</p></section></main>;
 if(!user)return null;
 const joined=new Date(user.createdAt);const joinedLabel=Number.isNaN(joined.getTime())?'Недавно':joined.toLocaleDateString('ru-RU',{month:'long',year:'numeric'});
 const visiblePosts=tab==='media'?posts.filter(p=>!!p.media_url):posts;const mediaCount=posts.filter(p=>!!p.media_url).length;
 const connectionPeople=connections==='followers'?followers:following;
 const connectionsModal=connections && <div className={styles.profileConnectionsBackdrop} role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setConnections(null)}}><section className={styles.profileConnections} role="dialog" aria-modal="true" aria-labelledby="connections-title"><div className={styles.profileConnectionsHead}><div><p className="eyebrow">NEXA NETWORK</p><h3 id="connections-title">{connections==='followers'?'Твои подписчики':'Твои подписки'}</h3></div><button type="button" className={styles.profileConnectionsClose} aria-label="Закрыть" onClick={()=>setConnections(null)}>×</button></div>{connectionsLoading?<p className="muted">Загрузка…</p>:connectionPeople.length===0?<p className="muted">Пока здесь никого нет.</p>:<div className={styles.profilePeopleList}>{connectionPeople.map(person=><Link key={person.id} href={`/users/${person.username}`} onClick={()=>setConnections(null)} className={styles.profilePerson}><span className={styles.profilePersonAvatar}>{person.avatarUrl?<img src={person.avatarUrl} alt=""/>:((person.displayName||person.username)[0]?.toUpperCase()||'N')}</span><span className={styles.profilePersonInfo}><strong>{person.displayName||person.username}</strong><small>@{person.username}</small><em>Открыть профиль →</em></span></Link>)}</div>}</section></div>;
 const renderPost=(post:Post)=><article className="post" key={post.id}><div className="post-head"><div className="mini-avatar gradient">{initial}</div><div><strong>{user.displayName||user.username}</strong><span>@{user.username} · {new Date(post.created_at).toLocaleString('ru-RU')}</span></div></div>{post.content&&<p className="post-text">{post.content}</p>}{post.media_url&&<img src={post.media_url} alt="Фото профиля" style={{display:'block',width:'100%',maxHeight:680,objectFit:'cover',borderRadius:20,marginTop:12,border:'1px solid rgba(255,255,255,.08)'}}/>}<div className="actions" style={{display:'flex',gap:8,marginTop:12,flexWrap:'wrap'}}><button className={post.liked?'liked':''} onClick={()=>like(post)}>♥ {post.like_count||0}</button><button onClick={()=>toggleComments(post)}>💬 {post.comment_count||0}</button><button onClick={()=>share(post)}>↗ Поделиться</button></div>{openComments[String(post.id)]&&<div className="comments">{(comments[String(post.id)]||[]).map(c=><div className="comment" key={c.id}><b>{c.username}</b><span>{c.content}</span></div>)}<div className="commentForm"><input value={commentText[String(post.id)]||''} onChange={e=>setCommentText(x=>({...x,[String(post.id)]:e.target.value}))} maxLength={1000} placeholder="Напиши комментарий…"/><button onClick={()=>addComment(post)}>Отправить</button></div></div>}</article>;
 return <main className="shell">
  <aside className="sidebar"><div className="brand">NEXA<span>.</span></div><nav><Link href="/">Home</Link><Link href="/search">Search</Link><Link href="/messages">Messages</Link><Link href="/notifications">Notifications</Link><Link className="active" href="/profile">Profile</Link><Link href="/settings">Settings</Link></nav></aside>
  <section className="feed">
   <header className="topbar"><div><p className="eyebrow">YOUR SPACE</p><h1>Профиль</h1></div><Link className="avatar" style={{overflow:'hidden'}} href="/profile">{user.avatarUrl?<img src={user.avatarUrl} alt="" style={{width:'100%',height:'100%',objectFit:'cover',display:'block'}}/>:initial}</Link></header>
   <section className="profile-hero"><div className="profile-cover"/><div className="profile-main"><div className="profile-avatar gradient">{user.avatarUrl?<img src={user.avatarUrl} alt="Аватар"/>:initial}</div><div className="profile-actions"><button className="profile-action primary" onClick={()=>{setError('');setEditing(true)}}>Редактировать</button><button className="profile-action secondary" onClick={()=>photoInputRef.current?.click()} disabled={uploading}>{uploading?'Загружаем…':'Добавить фото'}</button><input ref={photoInputRef} hidden type="file" accept="image/*" multiple onChange={uploadPhotos}/></div><h2>{user.displayName||user.username}</h2><p className="profile-username">@{user.username}</p>{user.bio?<p className="profile-bio">{user.bio}</p>:<p className="profile-bio muted">Добавь описание профиля</p>}<p className="profile-email">{user.email}</p>
    <div className={styles.profileStatsGrid}><div className={styles.profileStat}><strong>{posts.length}</strong><span>Публикации</span></div><button type="button" className={`${styles.profileStat} ${styles.profileStatButton}`} onClick={()=>refreshConnections('followers')}><strong>{followers.length}</strong><span>Подписчики</span></button><button type="button" className={`${styles.profileStat} ${styles.profileStatButton}`} onClick={()=>refreshConnections('following')}><strong>{following.length}</strong><span>Подписки</span></button><button type="button" className={styles.profileStat} onClick={()=>setTab('media')}><strong>{mediaCount}</strong><span>Фотографии</span></button></div>
   </div></section>
   {error&&<div style={{margin:'12px 0',padding:'12px 14px',border:'1px solid rgba(255,70,120,.28)',borderRadius:14,color:'#ff9ab8',background:'rgba(255,39,108,.08)'}}>{error}</div>}
   <div className="profile-tabs"><button className={tab==='posts'?'selected':''} onClick={()=>setTab('posts')}>Посты <span style={{opacity:.6}}>· {posts.length}</span></button><button className={tab==='media'?'selected':''} onClick={()=>setTab('media')}>Медиа <span style={{opacity:.6}}>· {mediaCount}</span></button><button disabled>Лайки</button></div>
   <section>{postsLoading?<div className="profile-empty"><h3>Загружаем публикации…</h3></div>:visiblePosts.length===0?<div className="profile-empty"><div className="profile-empty-icon">✦</div><h3>{tab==='media'?'Фотографий пока нет':'Твоё пространство'}</h3><p>{tab==='media'?'Добавь сколько угодно фотографий — ограничений по количеству нет.':'Создай первую публикацию или добавь фото.'}</p><button className="profile-action primary" onClick={()=>tab==='media'?photoInputRef.current?.click():router.push('/')}>{tab==='media'?'Добавить фото':'Создать пост →'}</button></div>:tab==='media'?<div className={styles.mediaGalleryV3}>{visiblePosts.map(post=><div key={post.id} className={styles.mediaCardV3}><img src={post.media_url||''} alt="Фото" className={styles.mediaImageV3} onClick={()=>window.open(post.media_url||'', '_blank')}/><div className={styles.mediaActionsV3}><button onClick={()=>like(post)} className={post.liked?'liked':''}>♥ {post.like_count||0}</button><button onClick={()=>toggleComments(post)}>💬 {post.comment_count||0}</button><button onClick={()=>share(post)}>↗</button></div>{openComments[String(post.id)]&&<div className="comments" style={{margin:0}}><div className="commentForm"><input value={commentText[String(post.id)]||''} onChange={e=>setCommentText(x=>({...x,[String(post.id)]:e.target.value}))} placeholder="Комментарий…"/><button onClick={()=>addComment(post)}>→</button></div></div>}</div>)}</div>:visiblePosts.map(renderPost)}</section>
  </section>
  {editing&&<div className="profile-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(false)}}><form className="profile-modal" onSubmit={save}><div className="profile-modal-head"><div><p className="eyebrow">NEXA PROFILE</p><h2>Редактировать профиль</h2></div><button type="button" className="modal-close" onClick={()=>setEditing(false)}>×</button></div><div className="avatar-editor"><div className="profile-avatar gradient avatar-editor-preview">{form.avatarUrl?<img src={form.avatarUrl} alt="Предпросмотр"/>:initial}</div><button type="button" className="profile-action secondary" onClick={()=>fileInputRef.current?.click()}>Выбрать фото</button><input ref={fileInputRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseAvatar}/></div><label>Имя<input value={form.displayName} maxLength={60} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>О себе<textarea value={form.bio} maxLength={160} rows={4} onChange={e=>setForm({...form,bio:e.target.value})}/></label>{error&&<p className="profile-form-error">{error}</p>}<div className="profile-modal-actions"><button type="button" className="profile-action secondary" onClick={()=>setEditing(false)}>Отмена</button><button className="profile-action primary" disabled={saving}>{saving?'Сохраняем…':'Сохранить'}</button></div></form></div>}
  {typeof document!=='undefined' && connectionsModal ? createPortal(connectionsModal,document.body) : null}
 </main>
}
