'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

type Track={id:string;username:string;title:string;description:string;media_url:string;like_count:number;comment_count:number};

export default function HomeMusicWidget(){
 const [tracks,setTracks]=useState<Track[]>([]);
 const [loading,setLoading]=useState(true);
 const [playing,setPlaying]=useState<string|null>(null);
 const [audio,setAudio]=useState<HTMLAudioElement|null>(null);
 useEffect(()=>{fetch('/api/media-library?kind=music',{cache:'no-store'}).then(r=>r.json()).then(d=>setTracks((d.items??[]).filter((x:Track)=>x.media_url).slice(0,3))).catch(()=>{}).finally(()=>setLoading(false));return()=>audio?.pause()},[]);
 const play=(t:Track)=>{if(playing===t.id){audio?.pause();setPlaying(null);return} audio?.pause();const a=new Audio(t.media_url);a.onended=()=>setPlaying(null);a.play().then(()=>{setAudio(a);setPlaying(t.id)}).catch(()=>setPlaying(null))};
 return <section className="home-music-widget" aria-label="Музыка на главной"><div className="home-music-head"><div><span>♫ NEXA MUSIC</span><h2>Музыка</h2></div><Link href="/media?tab=music">Вся музыка →</Link></div>{loading?<div className="home-music-empty">Загрузка треков…</div>:tracks.length===0?<div className="home-music-empty"><span>♫</span><div><b>Музыка рядом</b><small>Пока нет опубликованных треков</small></div><Link href="/media?tab=music">Открыть музыку</Link></div>:<div className="home-music-list">{tracks.map(t=><button className={`home-track ${playing===t.id?'is-playing':''}`} key={t.id} onClick={()=>play(t)}><span className="home-track-icon">{playing===t.id?'Ⅱ':'▶'}</span><span className="home-track-info"><b>{t.title}</b><small>@{t.username}</small></span><span className="home-track-stats">♥ {t.like_count}</span></button>)}</div>}<style>{`.home-music-widget{margin:0 0 18px;padding:16px;border:1px solid #1b1e27;background:rgba(12,14,19,.72);backdrop-filter:blur(18px);border-radius:18px;box-shadow:0 14px 45px rgba(0,0,0,.12)}.home-music-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.home-music-head span{font-size:9px;letter-spacing:2px;color:#777e8e}.home-music-head h2{margin:3px 0 0;font-size:20px}.home-music-head a{color:#aeb5c4;text-decoration:none;font-size:12px}.home-music-list{display:grid;gap:7px}.home-track{width:100%;display:flex;align-items:center;gap:11px;text-align:left;border:1px solid #242833;background:#0b0e14;color:#fff;border-radius:13px;padding:10px;cursor:pointer}.home-track:hover,.home-track.is-playing{border-color:#41485b;background:#11151e}.home-track-icon{width:34px;height:34px;display:grid;place-items:center;border-radius:10px;background:linear-gradient(135deg,#ff276c,#5c62ff);font-size:11px}.home-track-info{min-width:0;display:grid;gap:2px;flex:1}.home-track-info b{font-size:13px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.home-track-info small{font-size:10px;color:#777e8e}.home-track-stats{font-size:10px;color:#777e8e}.home-music-empty{min-height:60px;display:flex;align-items:center;gap:12px;color:#777e8e;font-size:12px}.home-music-empty>span{width:38px;height:38px;display:grid;place-items:center;border-radius:11px;background:#151925;color:#fff;font-size:18px}.home-music-empty div{display:grid;gap:3px;flex:1}.home-music-empty b{color:#dfe2e9;font-size:13px}.home-music-empty small{color:#707787}.home-music-empty a{font-size:11px;color:#fff;text-decoration:none;white-space:nowrap}@media(max-width:760px){.home-music-widget{margin-bottom:14px;padding:13px;border-radius:16px}.home-track{padding:9px}.home-track-stats{display:none}.home-music-head h2{font-size:18px}}`}</style></section>
}
